# Generated by Django 3.1.5 on 2021-01-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
